BEGIN TRY 
BEGIN TRANSACTION
IF DB_ID('TestCrudApi') IS NOT NULL
BEGIN
SELECT 'Database Name already Exist' AS Message
END
ELSE BEGIN
    CREATE DATABASE [TestCrudApi]
SELECT 'New Database is Created'
END
COMMIT TRANSACTION
END TRY 
BEGIN CATCH 
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
THROW
END CATCH